# Generated by Django 3.2.4 on 2021-06-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='json_obj',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
