# Generated by Django 3.2.4 on 2021-06-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_response_json_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='json_obj',
            new_name='json_object',
        ),
    ]
